# Generated by Django 4.2.5 on 2023-09-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesimilar',
            name='img1',
            field=models.CharField(max_length=300),
        ),
    ]
